---
os: linux
dist: bionic
jobs:
  include:
    - language: python
      python: 3.6
      cache: pip
      install:
        - pipenv lock --dev --requirements > /tmp/requirements.txt
        - pip install -r /tmp/requirements.txt
      script: docs/build_docs.sh

    - language: ruby
      services:
        - docker
      script:
        - docker build -t jwflory/django-rit-grasa:latest .
        - docker images -a
