version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Grasa-Django-App
    network_mode: host
    ports:
      - 80:8000
  db:
    image: "mariadb:10.1"
    volumes:
      - "~/.cache/django-rit-grasa-db:/var/lib/mysql:z"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=djangoGrasa2019
      - MYSQL_DATABASE=grasa_event_locator
      - MYSQL_USER=grasaadmin
      - MYSQL_PASSWORD=djangoGrasa2019

