version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 16000:8000
  db:
    image: "mariadb:10.1"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=djangoGrasa2019
      - MYSQL_DATABASE=grasa_event_locator
      - MYSQL_USER=grasaadmin
      - MYSQL_PASSWORD=djangoGrasa2019
