version: '3'
services:
  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./grasa_event_locator:/app/grasa_event_locator:z
  db:
    image: "mariadb:10.1"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=djangoGrasa2019
      - MYSQL_DATABASE=grasa_event_locator
      - MYSQL_USER=grasaadmin
      - MYSQL_PASSWORD=djangoGrasa2019
