# Generated by Django 2.2.5 on 2019-09-28 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=40)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('isPending', models.BooleanField(default=True)),
                ('image_reference', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=40)),
                ('website', models.CharField(max_length=40)),
                ('isPending', models.BooleanField(default=True)),
                ('editOf', models.IntegerField(default=None)),
                ('categories', models.ManyToManyField(to='grasa_event_locator.Category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grasa_event_locator.User')),
            ],
        ),
    ]
