# Generated by Django 2.2.5 on 2019-09-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grasa_event_locator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
