# Generated by Django 2.2.5 on 2019-10-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grasa_event_locator', '0002_auto_20191021_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='fees',
            field=models.FloatField(default=0),
        ),
    ]
