name: code quality

on:
  pull_request:
    branches:
    - master

jobs:
  black_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Reformat Python code with Black code formatter. https://github.com/psf/black
      uses: lgeiger/black-action@master
